#!/usr/bin/python3

import unittest

#from p01_dna_to_rna import dna_to_rna

from tmc import points

from tmc.utils import load, get_out

get_dict = load('src.codon_to_prob', 'get_dict')


@points('p07-05.1')
class TestCodonToProb(unittest.TestCase):



    def test_size(self):
        d = get_dict()
        self.assertEqual(len(d), 64)

    def test_content(self):
        d = get_dict()
        self.assertIn("UUU", d, msg="Codon UUU was not found in the dictionary!")
        self.assertEqual(d["UUU"], 0.46, msg="Incorrect probability of codon UUU!")
        self.assertIn("UCU", d, msg="Codon UCU was not found in the dictionary!")
        self.assertEqual(d["UCU"], 0.19, msg="Incorrect probability of codon UCU!")
        self.assertIn("UAU", d, msg="Codon UAU was not found in the dictionary!")
        self.assertEqual(d["UAU"], 0.44, msg="Incorrect probability of codon UAU!")
        self.assertIn("UGU", d, msg="Codon UGU was not found in the dictionary!")
        self.assertEqual(d["UGU"], 0.46, msg="Incorrect probability of codon UGU!")
        self.assertIn("UUC", d, msg="Codon UUC was not found in the dictionary!")
        self.assertEqual(d["UUC"], 0.54, msg="Incorrect probability of codon UUC!")
        self.assertIn("UCC", d, msg="Codon UCC was not found in the dictionary!")
        self.assertEqual(d["UCC"], 0.22, msg="Incorrect probability of codon UCC!")
        self.assertIn("UAC", d, msg="Codon UAC was not found in the dictionary!")
        self.assertEqual(d["UAC"], 0.56, msg="Incorrect probability of codon UAC!")
        self.assertIn("UGC", d, msg="Codon UGC was not found in the dictionary!")
        self.assertEqual(d["UGC"], 0.54, msg="Incorrect probability of codon UGC!")
        self.assertIn("UUA", d, msg="Codon UUA was not found in the dictionary!")
        self.assertEqual(d["UUA"], 0.08, msg="Incorrect probability of codon UUA!")
        self.assertIn("UCA", d, msg="Codon UCA was not found in the dictionary!")
        self.assertEqual(d["UCA"], 0.15, msg="Incorrect probability of codon UCA!")
        self.assertIn("UAA", d, msg="Codon UAA was not found in the dictionary!")
        self.assertEqual(d["UAA"], 0.3, msg="Incorrect probability of codon UAA!")
        self.assertIn("UGA", d, msg="Codon UGA was not found in the dictionary!")
        self.assertEqual(d["UGA"], 0.47, msg="Incorrect probability of codon UGA!")
        self.assertIn("UUG", d, msg="Codon UUG was not found in the dictionary!")
        self.assertEqual(d["UUG"], 0.13, msg="Incorrect probability of codon UUG!")
        self.assertIn("UCG", d, msg="Codon UCG was not found in the dictionary!")
        self.assertEqual(d["UCG"], 0.05, msg="Incorrect probability of codon UCG!")
        self.assertIn("UAG", d, msg="Codon UAG was not found in the dictionary!")
        self.assertEqual(d["UAG"], 0.24, msg="Incorrect probability of codon UAG!")
        self.assertIn("UGG", d, msg="Codon UGG was not found in the dictionary!")
        self.assertEqual(d["UGG"], 1.0, msg="Incorrect probability of codon UGG!")
        self.assertIn("CUU", d, msg="Codon CUU was not found in the dictionary!")
        self.assertEqual(d["CUU"], 0.13, msg="Incorrect probability of codon CUU!")
        self.assertIn("CCU", d, msg="Codon CCU was not found in the dictionary!")
        self.assertEqual(d["CCU"], 0.29, msg="Incorrect probability of codon CCU!")
        self.assertIn("CAU", d, msg="Codon CAU was not found in the dictionary!")
        self.assertEqual(d["CAU"], 0.42, msg="Incorrect probability of codon CAU!")
        self.assertIn("CGU", d, msg="Codon CGU was not found in the dictionary!")
        self.assertEqual(d["CGU"], 0.08, msg="Incorrect probability of codon CGU!")
        self.assertIn("CUC", d, msg="Codon CUC was not found in the dictionary!")
        self.assertEqual(d["CUC"], 0.2, msg="Incorrect probability of codon CUC!")
        self.assertIn("CCC", d, msg="Codon CCC was not found in the dictionary!")
        self.assertEqual(d["CCC"], 0.32, msg="Incorrect probability of codon CCC!")
        self.assertIn("CAC", d, msg="Codon CAC was not found in the dictionary!")
        self.assertEqual(d["CAC"], 0.58, msg="Incorrect probability of codon CAC!")
        self.assertIn("CGC", d, msg="Codon CGC was not found in the dictionary!")
        self.assertEqual(d["CGC"], 0.18, msg="Incorrect probability of codon CGC!")
        self.assertIn("CUA", d, msg="Codon CUA was not found in the dictionary!")
        self.assertEqual(d["CUA"], 0.07, msg="Incorrect probability of codon CUA!")
        self.assertIn("CCA", d, msg="Codon CCA was not found in the dictionary!")
        self.assertEqual(d["CCA"], 0.28, msg="Incorrect probability of codon CCA!")
        self.assertIn("CAA", d, msg="Codon CAA was not found in the dictionary!")
        self.assertEqual(d["CAA"], 0.27, msg="Incorrect probability of codon CAA!")
        self.assertIn("CGA", d, msg="Codon CGA was not found in the dictionary!")
        self.assertEqual(d["CGA"], 0.11, msg="Incorrect probability of codon CGA!")
        self.assertIn("CUG", d, msg="Codon CUG was not found in the dictionary!")
        self.assertEqual(d["CUG"], 0.4, msg="Incorrect probability of codon CUG!")
        self.assertIn("CCG", d, msg="Codon CCG was not found in the dictionary!")
        self.assertEqual(d["CCG"], 0.11, msg="Incorrect probability of codon CCG!")
        self.assertIn("CAG", d, msg="Codon CAG was not found in the dictionary!")
        self.assertEqual(d["CAG"], 0.73, msg="Incorrect probability of codon CAG!")
        self.assertIn("CGG", d, msg="Codon CGG was not found in the dictionary!")
        self.assertEqual(d["CGG"], 0.2, msg="Incorrect probability of codon CGG!")
        self.assertIn("AUU", d, msg="Codon AUU was not found in the dictionary!")
        self.assertEqual(d["AUU"], 0.36, msg="Incorrect probability of codon AUU!")
        self.assertIn("ACU", d, msg="Codon ACU was not found in the dictionary!")
        self.assertEqual(d["ACU"], 0.25, msg="Incorrect probability of codon ACU!")
        self.assertIn("AAU", d, msg="Codon AAU was not found in the dictionary!")
        self.assertEqual(d["AAU"], 0.47, msg="Incorrect probability of codon AAU!")
        self.assertIn("AGU", d, msg="Codon AGU was not found in the dictionary!")
        self.assertEqual(d["AGU"], 0.15, msg="Incorrect probability of codon AGU!")
        self.assertIn("AUC", d, msg="Codon AUC was not found in the dictionary!")
        self.assertEqual(d["AUC"], 0.47, msg="Incorrect probability of codon AUC!")
        self.assertIn("ACC", d, msg="Codon ACC was not found in the dictionary!")
        self.assertEqual(d["ACC"], 0.36, msg="Incorrect probability of codon ACC!")
        self.assertIn("AAC", d, msg="Codon AAC was not found in the dictionary!")
        self.assertEqual(d["AAC"], 0.53, msg="Incorrect probability of codon AAC!")
        self.assertIn("AGC", d, msg="Codon AGC was not found in the dictionary!")
        self.assertEqual(d["AGC"], 0.24, msg="Incorrect probability of codon AGC!")
        self.assertIn("AUA", d, msg="Codon AUA was not found in the dictionary!")
        self.assertEqual(d["AUA"], 0.17, msg="Incorrect probability of codon AUA!")
        self.assertIn("ACA", d, msg="Codon ACA was not found in the dictionary!")
        self.assertEqual(d["ACA"], 0.28, msg="Incorrect probability of codon ACA!")
        self.assertIn("AAA", d, msg="Codon AAA was not found in the dictionary!")
        self.assertEqual(d["AAA"], 0.43, msg="Incorrect probability of codon AAA!")
        self.assertIn("AGA", d, msg="Codon AGA was not found in the dictionary!")
        self.assertEqual(d["AGA"], 0.21, msg="Incorrect probability of codon AGA!")
        self.assertIn("AUG", d, msg="Codon AUG was not found in the dictionary!")
        self.assertEqual(d["AUG"], 1.0, msg="Incorrect probability of codon AUG!")
        self.assertIn("ACG", d, msg="Codon ACG was not found in the dictionary!")
        self.assertEqual(d["ACG"], 0.11, msg="Incorrect probability of codon ACG!")
        self.assertIn("AAG", d, msg="Codon AAG was not found in the dictionary!")
        self.assertEqual(d["AAG"], 0.57, msg="Incorrect probability of codon AAG!")
        self.assertIn("AGG", d, msg="Codon AGG was not found in the dictionary!")
        self.assertEqual(d["AGG"], 0.21, msg="Incorrect probability of codon AGG!")
        self.assertIn("GUU", d, msg="Codon GUU was not found in the dictionary!")
        self.assertEqual(d["GUU"], 0.18, msg="Incorrect probability of codon GUU!")
        self.assertIn("GCU", d, msg="Codon GCU was not found in the dictionary!")
        self.assertEqual(d["GCU"], 0.27, msg="Incorrect probability of codon GCU!")
        self.assertIn("GAU", d, msg="Codon GAU was not found in the dictionary!")
        self.assertEqual(d["GAU"], 0.46, msg="Incorrect probability of codon GAU!")
        self.assertIn("GGU", d, msg="Codon GGU was not found in the dictionary!")
        self.assertEqual(d["GGU"], 0.16, msg="Incorrect probability of codon GGU!")
        self.assertIn("GUC", d, msg="Codon GUC was not found in the dictionary!")
        self.assertEqual(d["GUC"], 0.24, msg="Incorrect probability of codon GUC!")
        self.assertIn("GCC", d, msg="Codon GCC was not found in the dictionary!")
        self.assertEqual(d["GCC"], 0.4, msg="Incorrect probability of codon GCC!")
        self.assertIn("GAC", d, msg="Codon GAC was not found in the dictionary!")
        self.assertEqual(d["GAC"], 0.54, msg="Incorrect probability of codon GAC!")
        self.assertIn("GGC", d, msg="Codon GGC was not found in the dictionary!")
        self.assertEqual(d["GGC"], 0.34, msg="Incorrect probability of codon GGC!")
        self.assertIn("GUA", d, msg="Codon GUA was not found in the dictionary!")
        self.assertEqual(d["GUA"], 0.12, msg="Incorrect probability of codon GUA!")
        self.assertIn("GCA", d, msg="Codon GCA was not found in the dictionary!")
        self.assertEqual(d["GCA"], 0.23, msg="Incorrect probability of codon GCA!")
        self.assertIn("GAA", d, msg="Codon GAA was not found in the dictionary!")
        self.assertEqual(d["GAA"], 0.42, msg="Incorrect probability of codon GAA!")
        self.assertIn("GGA", d, msg="Codon GGA was not found in the dictionary!")
        self.assertEqual(d["GGA"], 0.25, msg="Incorrect probability of codon GGA!")
        self.assertIn("GUG", d, msg="Codon GUG was not found in the dictionary!")
        self.assertEqual(d["GUG"], 0.46, msg="Incorrect probability of codon GUG!")
        self.assertIn("GCG", d, msg="Codon GCG was not found in the dictionary!")
        self.assertEqual(d["GCG"], 0.11, msg="Incorrect probability of codon GCG!")
        self.assertIn("GAG", d, msg="Codon GAG was not found in the dictionary!")
        self.assertEqual(d["GAG"], 0.58, msg="Incorrect probability of codon GAG!")
        self.assertIn("GGG", d, msg="Codon GGG was not found in the dictionary!")
        self.assertEqual(d["GGG"], 0.25, msg="Incorrect probability of codon GGG!")


if __name__ == '__main__':
    unittest.main()

